/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_ycsb_db_JAnanas */

#ifndef _Included_com_yahoo_ycsb_db_JAnanas
#define _Included_com_yahoo_ycsb_db_JAnanas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_ycsb_db_JAnanas
 * Method:    connect
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_yahoo_ycsb_db_JAnanas_connect
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_yahoo_ycsb_db_JAnanas
 * Method:    disconnect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_ycsb_db_JAnanas_disconnect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yahoo_ycsb_db_JAnanas
 * Method:    createTable
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_yahoo_ycsb_db_JAnanas_createTable__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_yahoo_ycsb_db_JAnanas
 * Method:    createTable
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_yahoo_ycsb_db_JAnanas_createTable__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_yahoo_ycsb_db_JAnanas
 * Method:    dropTable
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_ycsb_db_JAnanas_dropTable
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_yahoo_ycsb_db_JAnanas
 * Method:    getTableId
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_yahoo_ycsb_db_JAnanas_getTableId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_yahoo_ycsb_db_JAnanas
 * Method:    read
 * Signature: (J[B)Lcom/yahoo/ycsb/db/JAnanas/Object;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_ycsb_db_JAnanas_read
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_yahoo_ycsb_db_JAnanas
 * Method:    remove
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_yahoo_ycsb_db_JAnanas_remove
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_yahoo_ycsb_db_JAnanas
 * Method:    write
 * Signature: (J[B[B)J
 */
JNIEXPORT jlong JNICALL Java_com_yahoo_ycsb_db_JAnanas_write
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
