/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_ycsb_db_JAnanas_Object */

#ifndef _Included_com_yahoo_ycsb_db_JAnanas_Object
#define _Included_com_yahoo_ycsb_db_JAnanas_Object
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
