/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_ycsb_db_JAnanas_WrongVersionException */

#ifndef _Included_com_yahoo_ycsb_db_JAnanas_WrongVersionException
#define _Included_com_yahoo_ycsb_db_JAnanas_WrongVersionException
#ifdef __cplusplus
extern "C" {
#endif
#undef com_yahoo_ycsb_db_JAnanas_WrongVersionException_serialVersionUID
#define com_yahoo_ycsb_db_JAnanas_WrongVersionException_serialVersionUID -3042686055658047285LL
#undef com_yahoo_ycsb_db_JAnanas_WrongVersionException_serialVersionUID
#define com_yahoo_ycsb_db_JAnanas_WrongVersionException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
